<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <NoWarn>$(NoWarn);NU5128;NU5125;CS8017</NoWarn>
    <NuspecFile>Tesseract.Native.nuspec</NuspecFile>
    <NuspecBasePath>$(MSBuildProjectDirectory)</NuspecBasePath>
  </PropertyGroup>

</Project>
